# Site settings
name: Less Or More
email: luoyan35714@126.com
author: xiaolue
url: 
resume_site: 
github: https://github.com/wangjikui007/
baseurl: "/test1"
description: Actually, less is more!
meta_description: 王之略;个人博客;宁鸣而死;不默而生
motto: It's our wits that make us men.
banner: 宁鸣而死，不默而生。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9
